lotBackend/parkinglot/urls.py
from django.conf.urls import url, include
from parkinglot import views

app_name = 'api'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^api/customers/$', views.customers, name='customers'),
    url(r'^api/customers/(?P<pk>[0-9]*)$', views.customers_detail),
    url(r'^api/reservations/$', views.reservations, name='reservations'),
    url('^api/parkingSlots/$', views.parkingSlots, name='parkingSlots'),
    url('^api/parkingLots/$', views.parkingLots, name='parkinglots'),
    url('^api/parkingStatus/.*$', views.parkingStatus, name='parkingStatus'),
    url('^api/createParkingLot/$', views.createParkingLot, name='createParkingLot'),
]

lotBackend/src/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from parkinglot import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('parkinglot.urls')),
]

lotBackend/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>PARKING_LOT</title>
  </head>
  <body>
    <h3>Welcome to the parking Lot</h3>
    <a href="{% url 'api:createParkingLot' %}">Create a parking Lot</a>
    <br style = “line-height:5;”><br><a href="{% url 'api:customers' %}">Add a Customer</a>
    <br style = “line-height:5;”><br><a href="{% url 'api:parkingStatus' %}">Parking Slots Status</a>
    <br style = “line-height:5;”><br><a href="{% url 'api:reservations' %}">Add a parking slot reservation</a>

  </body>
</html>